#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Apr 18 20:55:48 2021

@author: victor
"""
# IMPORTS ------------------------------------------------------------------- #
import numpy as np
# IMPORTS ------------------------------------------------------------------- #
'''
DESCRIPTION


DESCRIPTION
'''
# Arrays to collect values
l2_exp_tA = np.array([])

# Array of values between 0 to 20
t = np.linspace(0, 20)

for ii in range(10):
    # 10x10 matrix of normally distributed values minus 2 times the identity
    # matrix.
    A = np.random.normal(0, 1, (10, 10)) - 2*np.identity(10)
    
    for t_val in t:
        
        # L-2 norm of exp(t*A)
        l2_exp_tA_val = np.linalg.norm(np.exp(t_val*A))
        